# This is the config file to put in credentials for the various services
# used in the examples.

# Note that you do not need have all of these values to run an example.
# Just add or modify the credentials you need for the example you
# want to run.

# Here's where the IronWorker project_id and token(s) go. They should
# be assigned within the IronWorker config block within your application.
# You can have multiple projects and create multiple tokens.

# IronWorker credentials
iw:
    token: ogIkJ..
    project_id: 4e..

# AWS credentials
# For s3, use an existing bucket name or create one in s3 if it doesn't exist.
aws:
    access_key: 3VXW4DQ... 
    secret_key: UxlTI4X... 
    s3_bucket_name: worker_test
    sdb_domain_prefix: worker_test_

# Databasecool credentials
mongo:
    host: somehost.mongohq.com
    port: 12345
    db_name: worker_test
    username: ausername
    password: apassword

mongo2:
    host: somehost.mongohq.com
    port: 12345
    db_name: worker_test
    username: ausername
    password: apassword
        
# mongo://<username>:<password>@<server>:<port>/<database>
mongo_uri: //ausername:apassword@somehost.mongohq.com:12345/worker_test

redis:
    hostname: somehost.redistogo.com
    port: 1234
    node_id: 0dcb21a9a94f956... 
    username: ausername
    password: apassword

# Format for URI: redis://foo:<password>@<hostname>:<port>/
redis_uri: //ausername:0dcb21a9a94f956...@somehost.redistogo.com:1234/
        
xeround:
    host: ec2-255...compute-1.amazonaws.com:1234
    port: 1234
    db_name: worker_test
    username: ausername
    password: apassword

mysql:
  host: ec2-218....compute-1.amazonaws.com:1234 
  port: 1234
  db_name: worker_test
  username: ausername
  password: apassword

#mysql2://localhost/blog?user=user&password=password')
mysql_uri: mysql2//username:password@host:port/db_name

# API services credentials
indextank:
    url: http://:96Ocudh....api.indextank.com
    index: index_test_people

klout:
    api_key: h9hvvac...
    twitter_names: ["ironworker", "chadarimura", "klout", "techcrunch", "monkchips", "aplusk", "sgblank", "venturehacks", "no_user_12345xyz"]

face:
    api_key:
    secret_key:
    
get_exceptional:
    api_key: 5684cb9f5...

notifo:
    service_user: 
    service_api: 
    task: subscribe
    username:
    message:

# Change the channel to what you want. The message is generally JSON.
pubnub:
    publish: pub-932990fa-0a9e-...
    subscribe: sub-bda8023e-0fb1-...
    secret: sec-690c5045-c02a-...
    channel: ironworker_test_channel
    message: Testing PubNub with IronWorker

pusher:
    key: c7a89381b... 
    secret: 10aa2a6b2... 
    app_id: 10967

twilio:
    sid: cb5389460bc8... 
    token: 41c8f9a42ab0f... 
    api_version: 2010-04-01
    from: +SANDBOX
    to: +YOURNUMBER
    message: Ironworker texting this using Twilio
    
twitter:
    consumer_key: 
    consumer_secret: 
    oauth_token: 
    oauth_token_secret: 
    message:
      
    
hipchat:
    api_key: ZZZ
    room_name: MY ROOM NAME
    twitter_keyword: ironworker
      
# Email credentials
gmail:
    domain: gmail.com
    username: sample_user
    password: secret_password
    
email:
    domain: somedomain.com
    username: user_name
    password: password
    from: somebody@acme.com
    to: somebodyelse@gmail.com
    provider: gmail

loggly:
    key: my_loggly_key

# Image files and other data files used in the examples
image_url: "http://fitnessgurunyc.com/wp/wp-content/uploads/2010/12/ironman74.jpg"
file_name: sample_image.png
